name: Fetch Authors Info

on:
  push:
    branches:
      - main  # Adjust branch name if necessary
  workflow_dispatch:

jobs:
  fetch-authors-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Authors Info and Send to Webhook
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          CONTRIBUTORS=$(curl -H "Authorization: token $GH_TOKEN" -s https://api.github.com/repos/rebelonion/Dantotsu/contributors)

          MESSAGE="Contributors Information:\n"

          echo "$CONTRIBUTORS" | jq -c '.[]' | while read -r contributor; do
            LOGIN=$(echo "$contributor" | jq -r '.login')
            COMMITS=$(echo "$contributor" | jq -r '.contributions')

            USER_DETAILS=$(curl -H "Authorization: token $GH_TOKEN" -s https://api.github.com/users/$LOGIN)
            NICKNAME=$(echo "$USER_DETAILS" | jq -r '.name // "N/A"')

            MESSAGE="$MESSAGE\nNickname: $NICKNAME, Login: $LOGIN, Commits: $COMMITS"
          done

          curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"$MESSAGE\"}" $DISCORD_WEBHOOK
